package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.scene.control.MenuItem;
import javafx.scene.control.RadioButton;
import javafx.scene.input.KeyEvent;
import model.AeropuertoPublico;
import javafx.scene.control.TableView;
import javafx.scene.control.Menu;
import javafx.scene.control.TableColumn;

public class AeropuertosController implements Initializable {
	@FXML
	private Menu menuAeropuertos;
	@FXML
	private MenuItem mtAnadirAeropuertos;
	@FXML
	private MenuItem mtEditarAeropuertos;
	@FXML
	private MenuItem mtBorrarAeropuertos;
	@FXML
	private MenuItem mtMostrarAeropuertos;
	@FXML
	private Menu menuAviones;
	@FXML
	private MenuItem mtAnadirAvion;
	@FXML
	private MenuItem mtActivarAviones;
	@FXML
	private MenuItem mtBorrar;
	@FXML
	private MenuItem mtAyudaAviones;
	@FXML
	private RadioButton rbPublico;
	@FXML
	private RadioButton rbPrivado;
	@FXML
	private TextField tfFiltro;
	@FXML
	private TableView<AeropuertoPublico> table;
	@FXML
	private TableColumn<AeropuertoPublico, Integer> cID;
	@FXML
	private TableColumn<AeropuertoPublico, String> cNombre;
	@FXML
	private TableColumn<AeropuertoPublico, String> cPais;
	@FXML
	private TableColumn<AeropuertoPublico, String> cCiudad;
	@FXML
	private TableColumn<AeropuertoPublico, String> cCalle;
	@FXML
	private TableColumn<AeropuertoPublico, Integer> cNumeroAsientos;
	@FXML
	private TableColumn<AeropuertoPublico, Integer> cYear;
	@FXML
	private TableColumn<AeropuertoPublico, Integer> cCapacidad;
	@FXML
	private TableColumn<AeropuertoPublico, Integer> cNSocios;

	// Event Listener on MenuItem[#mtAnadirAeropuertos].onAction
	@FXML
	public void anadirAeropuertos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtEditarAeropuertos].onAction
	@FXML
	public void editarAeropuertos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtBorrarAeropuertos].onAction
	@FXML
	public void borrarAeropuertos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtMostrarAeropuertos].onAction
	@FXML
	public void mostrarAeropuertos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtAnadirAvion].onAction
	@FXML
	public void anadirAvion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtActivarAviones].onAction
	@FXML
	public void activarAviones(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtBorrar].onAction
	@FXML
	public void borrarAviones(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtAyudaAviones].onAction
	@FXML
	public void ayudaAviones(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfFiltro].onKeyPressed
	@FXML
	public void filtrarNombre(KeyEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		cID.setCellValueFactory(new PropertyValueFactory<>("id"));
		cNombre.setCellValueFactory(new PropertyValueFactory<>("nombre"));
		cPais.setCellValueFactory(new PropertyValueFactory<>("pais"));
		cCiudad.setCellValueFactory(new PropertyValueFactory<>("ciudad"));
		cCalle.setCellValueFactory(new PropertyValueFactory<>("calle"));
		cNumeroAsientos.setCellValueFactory(new PropertyValueFactory<>("numero"));
		cYear.setCellValueFactory(new PropertyValueFactory<>("age"));
		cCapacidad.setCellValueFactory(new PropertyValueFactory<>("capacidadNSocios"));
		cNSocios.setCellValueFactory(new PropertyValueFactory<>("capacidadNSocios"));
		
	}
}
