package controller;

import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;
import javafx.scene.control.MenuItem;
import javafx.scene.control.RadioButton;
import javafx.scene.input.KeyEvent;
import javafx.scene.control.TableView;
import javafx.scene.control.Menu;
import javafx.scene.control.TableColumn;

public class AeropuertosController {
	@FXML
	private Menu menuAeropuertos;
	@FXML
	private MenuItem mtAnadirAeropuertos;
	@FXML
	private MenuItem mtEditarAeropuertos;
	@FXML
	private MenuItem mtBorrarAeropuertos;
	@FXML
	private MenuItem mtMostrarAeropuertos;
	@FXML
	private Menu menuAviones;
	@FXML
	private MenuItem mtAnadirAvion;
	@FXML
	private MenuItem mtActivarAviones;
	@FXML
	private MenuItem mtBorrar;
	@FXML
	private MenuItem mtAyudaAviones;
	@FXML
	private RadioButton rbPublico;
	@FXML
	private RadioButton rbPrivado;
	@FXML
	private TextField tfFiltro;
	@FXML
	private TableView table;
	@FXML
	private TableColumn cID;
	@FXML
	private TableColumn cNombre;
	@FXML
	private TableColumn cPais;
	@FXML
	private TableColumn cCiudad;
	@FXML
	private TableColumn cCalle;
	@FXML
	private TableColumn cNumeroAsientos;
	@FXML
	private TableColumn cYear;
	@FXML
	private TableColumn cCapacidad;
	@FXML
	private TableColumn cNSocios;

	// Event Listener on MenuItem[#mtAnadirAeropuertos].onAction
	@FXML
	public void anadirAeropuertos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtEditarAeropuertos].onAction
	@FXML
	public void editarAeropuertos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtBorrarAeropuertos].onAction
	@FXML
	public void borrarAeropuertos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtMostrarAeropuertos].onAction
	@FXML
	public void mostrarAeropuertos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtAnadirAvion].onAction
	@FXML
	public void anadirAvion(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtActivarAviones].onAction
	@FXML
	public void activarAviones(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtBorrar].onAction
	@FXML
	public void borrarAviones(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mtAyudaAviones].onAction
	@FXML
	public void ayudaAviones(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfFiltro].onKeyPressed
	@FXML
	public void filtrarNombre(KeyEvent event) {
		// TODO Autogenerated
	}
}
