package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ToggleGroup;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

public class AeropuertosAnadirEditarController {
	@FXML
	private RadioButton rbPublico;
	@FXML
	private ToggleGroup publicoPrivado;
	@FXML
	private RadioButton rbPrivado;
	@FXML
	private TextField tfNombre;
	@FXML
	private TextField tfPais;
	@FXML
	private TextField tfCiudad;
	@FXML
	private TextField tfCalle;
	@FXML
	private TextField tfNumero;
	@FXML
	private TextField tfAnioInaguracion;
	@FXML
	private TextField tfCapacidad;
	@FXML
	private TextField tfFinancia;
	@FXML
	private TextField tfNTrabajadores;
	@FXML
	private Button btnGuardar;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnGuardar].onAction
	@FXML
	public void guardar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
