package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ToggleGroup;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

import javafx.scene.control.Spinner;

public class AvionAnadirDesactivarController {
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnDesactivar;
	@FXML
	private RadioButton rbActivado;
	@FXML
	private ToggleGroup activadoDesactivado;
	@FXML
	private RadioButton rbDesactivado;
	@FXML
	private TextField tfModelo;
	@FXML
	private TextField tfAsientos;
	@FXML
	private TextField tfVelocidadM;
	@FXML
	private Spinner spinAeropuertos;

	@FXML
	public void activado(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void desactivado(ActionEvent event) {
		// TODO Autogenerated
	}
}
