package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Spinner;

public class borrarAvionController {
	@FXML
	private Button btnBoorrar;
	@FXML
	private Button brnCancelar;
	@FXML
	private Spinner spinAviones;
	@FXML
	private Spinner spinAeropuertos;

	// Event Listener on Button[#btnBoorrar].onAction
	@FXML
	public void borrar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#brnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
